# Generated by Django 3.2.8 on 2021-10-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tomperrus', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
                ('Image', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=1024)),
            ],
        ),
    ]
