# Generated by Django 3.2.8 on 2021-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0006_products_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
