# Generated by Django 3.2.8 on 2021-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0007_auto_20211017_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.TextField(),
        ),
    ]
