# Generated by Django 3.2.8 on 2021-10-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0008_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavor1', models.CharField(blank=True, max_length=32)),
                ('Flavor2', models.CharField(blank=True, max_length=32)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tomperrus.products')),
            ],
        ),
    ]
