# Generated by Django 3.2.8 on 2021-10-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0008_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavor1', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Ingredients', models.TextField()),
                ('Validade', models.TextField()),
                ('FlavorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tomperrus.flavor')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tomperrus.product')),
            ],
        ),
        migrations.AddField(
            model_name='flavor',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tomperrus.product'),
        ),
    ]
