# Generated by Django 3.2.8 on 2021-10-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0009_auto_20211018_1523'),
        ('Tomperrus', '0009_flavors'),
    ]

    operations = [
    ]
