# Generated by Django 3.2.8 on 2021-10-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0010_merge_0009_auto_20211018_1523_0009_flavors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavors',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='rotulo',
            name='FlavorName',
        ),
        migrations.RemoveField(
            model_name='rotulo',
            name='Name',
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='Flavors',
        ),
        migrations.DeleteModel(
            name='Rotulo',
        ),
    ]
