# Generated by Django 3.2.8 on 2021-10-18 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0011_auto_20211018_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flavour1', models.CharField(max_length=32)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tomperrus.product')),
            ],
        ),
    ]
