# Generated by Django 3.2.8 on 2021-10-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0013_auto_20211018_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavour',
            old_name='Ingredientes',
            new_name='Ingredients',
        ),
    ]
