# Generated by Django 3.2.8 on 2021-10-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0014_rename_ingredientes_flavour_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavour',
            old_name='Product',
            new_name='ProductN',
        ),
    ]
