# Generated by Django 3.2.8 on 2021-10-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0015_rename_product_flavour_productn'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='Product_id',
            field=models.IntegerField(blank=True, default='3'),
        ),
    ]
