# Generated by Django 3.2.8 on 2021-10-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0016_flavour_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='Product_id',
        ),
    ]
