# Generated by Django 3.2.8 on 2021-10-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0018_rename_productn_flavour_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavour',
            old_name='Product_id',
            new_name='product_id',
        ),
    ]
