# Generated by Django 3.2.8 on 2021-10-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0020_rename_product_id_flavour_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavour',
            old_name='product',
            new_name='ProductN',
        ),
    ]
