# Generated by Django 3.2.8 on 2021-10-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0021_rename_product_flavour_productn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='Validade',
        ),
        migrations.AddField(
            model_name='product',
            name='Validade',
            field=models.TextField(blank=True, default='Valide de 60 dias; Conservar o produto refrigeração; Após aberto consumir em 30 dias.'),
        ),
    ]
