# Generated by Django 3.2.8 on 2021-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0023_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='Color',
            field=models.CharField(default='green', max_length=64, verbose_name='Inglês'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Validade',
            field=models.TextField(blank=True, default='Validade de 60 dias; Conservar o produto refrigeração; Após aberto consumir em 30 dias.'),
        ),
    ]
