# Generated by Django 3.2.8 on 2021-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0024_auto_20211021_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='Color',
            field=models.CharField(blank=True, default='green', max_length=64, verbose_name='Inglês'),
        ),
    ]
