# Generated by Django 3.2.8 on 2021-10-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0025_alter_flavour_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='Color',
            field=models.CharField(blank=True, default='green', max_length=64),
        ),
    ]
