# Generated by Django 3.2.8 on 2021-10-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0026_alter_flavour_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageFile', models.ImageField(blank=True, upload_to='static/assets')),
                ('Image1', models.CharField(blank=True, max_length=64)),
                ('ProductN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tomperrus.product')),
            ],
        ),
    ]
