# Generated by Django 3.2.8 on 2021-11-01 12:19

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0032_auto_20211101_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ImageFile',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='static/images'), upload_to='static/images'),
        ),
    ]
