# Generated by Django 3.2.8 on 2021-11-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0034_alter_product_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.CharField(default='media/images/NOME DO ARQUIVO', max_length=64),
        ),
    ]
