# Generated by Django 3.2.8 on 2021-11-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0035_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image1',
        ),
        migrations.AlterField(
            model_name='image',
            name='Image1',
            field=models.CharField(blank=True, default='media/images/NOME DO ARQUIVO', max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='ImageFile',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
