# Generated by Django 3.2.8 on 2021-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0037_product_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.CharField(default='../../media/images/NOME DO ARQUIVO', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image1',
            field=models.CharField(blank=True, default='../../media/images/NOME DO ARQUIVO', max_length=64),
        ),
    ]
