# Generated by Django 3.2.8 on 2021-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomperrus', '0038_auto_20211101_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image1',
        ),
        migrations.AddField(
            model_name='product',
            name='ImageFile1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
